/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import { Platform } from 'react-native';

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#1F1F1F',
    background: '#F6EDE3',
    sidebarBackground: '#F7DFCF',
    activeBackground: '#E7A79A',
    footerBackground: '#E5ADA0',
    footerIcon: '#1F1F1F',
    themeToggleBackground: '#FFFFFF',
    logoutButtonBackground: '#FFFFFF',
    logoutButtonText: '#1F1F1F',
    textPrimary: '#1F1F1F',
    textSecondary: '#595959',
    activeText: '#1F1F1F',
    icon: '#121111',
    // Dashboard overview colors
    headerText: '#1A1A1A',
    cardBackground: '#F6E8DC',
    highlightText: '#C3473D',
    iconAccent: '#C3473D',
    divider: '#E4D5CA',
    badgeBackground: '#EDD5C5',
    avatarBackground: '#F0CFC2',
    avatarText: '#643022',
    transactionNegativeIconBackground: '#FAD9D9',
    transactionNegativeIcon: '#B2383B',
    transactionPositiveIconBackground: '#DFF3E3',
    transactionPositiveIcon: '#2F7A3D',
    transactionNegativeBadgeBackground: '#F5CFCF',
    transactionNegativeBadgeText: '#B2383B',
    transactionPositiveBadgeBackground: '#D6F0DA',
    transactionPositiveBadgeText: '#2F7A3D',
    transactionNegativeText: '#B2383B',
    transactionPositiveText: '#2F7A3D',
    // Login colors
    accent: '#D04940',
    accentPressed: '#B63D36',
    inputBackground: '#FFFFFF',
    inputBorder: '#E2D1C3',
    error: '#B3261E',
    iconAccentLight: '#FFFFFF',
    // Table/List colors
    activeTabBackground: '#E7A79A',
    inactiveTabBackground: '#E4D5CA',
    activeTabText: '#1F1F1F',
    inactiveTabText: '#5C5C5C',
    searchBackground: '#FFFFFF',
    searchBorder: '#E4D5CA',
    rowBackground: '#FFFFFF',
    rowBorder: '#E4D5CA',
    badgeSent: '#22C55E',
    badgeAssigned: '#3B82F6',
    badgeNotSent: '#9CA3AF',
    badgeHigh: '#22C55E',
    badgeMedium: '#F59E0B',
    badgeLow: '#F97316',
    badgeInactive: '#DC2626',
    buttonPrimary: '#C3473D',
    buttonSecondary: '#E4D5CA',
    buttonDanger: '#DC2626',
    tint: tintColorLight,
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#FFFFFF',
    background: '#000000',
    sidebarBackground: '#1A1A1A',
    activeBackground: '#2A2A2A',
    footerBackground: '#1A1A1A',
    footerIcon: '#FFFFFF',
    themeToggleBackground: '#2A2A2A',
    logoutButtonBackground: '#2A2A2A',
    logoutButtonText: '#FFFFFF',
    textPrimary: '#FFFFFF',
    textSecondary: '#CCCCCC',
    activeText: '#FFFFFF',
    icon: '#FFFFFF',
    // Dashboard overview colors (dark mode)
    headerText: '#FFFFFF',
    cardBackground: '#1A1A1A',
    highlightText: '#FF6B6B',
    iconAccent: '#FF6B6B',
    divider: '#333333',
    badgeBackground: '#2A2A2A',
    avatarBackground: '#2A2A2A',
    avatarText: '#FFFFFF',
    transactionNegativeIconBackground: '#4A1F1F',
    transactionNegativeIcon: '#FF6B6B',
    transactionPositiveIconBackground: '#1F4A1F',
    transactionPositiveIcon: '#4CAF50',
    transactionNegativeBadgeBackground: '#4A1F1F',
    transactionNegativeBadgeText: '#FF6B6B',
    transactionPositiveBadgeBackground: '#1F4A1F',
    transactionPositiveBadgeText: '#4CAF50',
    transactionNegativeText: '#FF6B6B',
    transactionPositiveText: '#4CAF50',
    // Login colors (dark mode)
    accent: '#D04940',
    accentPressed: '#B63D36',
    inputBackground: '#1A1A1A',
    inputBorder: '#333333',
    error: '#FF6B6B',
    iconAccentLight: '#FFFFFF',
    // Table/List colors (dark mode)
    activeTabBackground: '#2A2A2A',
    inactiveTabBackground: '#1A1A1A',
    activeTabText: '#FFFFFF',
    inactiveTabText: '#CCCCCC',
    searchBackground: '#1A1A1A',
    searchBorder: '#333333',
    rowBackground: '#1A1A1A',
    rowBorder: '#333333',
    badgeSent: '#22C55E',
    badgeAssigned: '#3B82F6',
    badgeNotSent: '#9CA3AF',
    badgeHigh: '#22C55E',
    badgeMedium: '#F59E0B',
    badgeLow: '#F97316',
    badgeInactive: '#DC2626',
    buttonPrimary: '#C3473D',
    buttonSecondary: '#2A2A2A',
    buttonDanger: '#FF6B6B',
    tint: tintColorDark,
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
  },
};

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
